# PATHS
src.dir=app/src/main/java
web.dir=app/src/main/webapp
build.dir=app/build
classes.dir=${build.dir}/classes
lib.dir=${build.dir}/libs
dist.dir=${build.dir}/dist

# WAR
war.name=server.war
main.class=org.itmo.controller.MakePoint
version=1.0.0

# TESTS
test.src.dir=app/src/test/java
test.classes.dir=${build.dir}/classes/java/test
test.report.dir=${build.dir}/test-reports
junit.version=5.10.0
junit.platform.version=1.10.0

# I18N
resources.dir=app/src/main/resources
n2a.src=resources
n2a.dest=resources/ascii

# REPLACE REGEX (ALT)
replace.pattern.old=org\.itmo
replace.pattern.new=org\.itmo\.alt

# MISC
javadoc.dir=${build.dir}/javadoc
git.repo=file:///path/to/reporepo